### PR TITLE
Added webpack-dev-server and semantic ui

### PR DESCRIPTION
**Pull request by bbaksh**
- Added webpack-dev-server (now you can save in the text editor and webpack will run again)
- Updated npm run dev script to use webpack-dev-server
- Added index.html and "app" div to be the root of our react rendering
- Linked semantic ui in the index.html
- Installed semantic ui to the project

### CODE REVIEW

**Comment by JoeRoussy** [comment]
This is out of pure curiosity, but why are we using a .js file instead of a .jsx file?

**Comment by bbaksh** [comment]
Just how webpack finds files, alternatively in webpack i could find files with js or jsx

**Comment by JoeRoussy** [comment]
I though jsx meant you can write pure XML (ie HTML) in the file itself but I see that you are doing that in the js files. Interesting that this works.

I am ok with going with the js files if it works, although it might cause syntax highlighting issues on some editors

**Comment by bbaksh** [comment]
Well we should decide on a standard for the project soon. Using jsx is ok as I can edit webpack to transpile on js and jsx.

**Comment by JoeRoussy** [comment]
Yeah I think we should use jsx

**Pull request merged**
